### ISSUE TITLE
testendpoint.py

### ISSUE THREAD

**Issue by DanRod1** [sarartur/chess.com#13]
Hi,
I am trying to understand the chess.com api wrapper and to begin I just try the testendpoint to see the format of the data retrieve.
I have troubles with this :
  data = client.get_player_profile("fabianocaruana")
  assert isinstance(data, ChessDotComResponse)

the assert havev a exception with no description 
If I try with a simple curl a retrieve a json correctly.

Anay Idea

**Comment by ghost** [comment]
@DanRod1, I don't see any exceptions being thrown when testing this. Since the `assert` functionality is for testing the viability of the actual program, it shouldn't return anything

True (returns nothing) = Good
False (returns something) = Bad

If you run the following snippet, you'll see what I mean:

```python
from chessdotcom import get_player_profile
from chessdotcom.types import ChessDotComResponse

data = get_player_profile("fabianocaruana")
print(isinstance(data, ChessDotComResponse)) # returns True since I'm using print()
```

If all you're trying to do is retrieve the data from the API, you just need to run something like this. No need to actually call the response class. Here's my example to print the JSON from the response:

```python
from chessdotcom import get_player_profile
from chessdotcom.types import ChessDotComResponse

data = get_player_profile("fabianocaruana")
print(data.json)
```

You could then do something like this to parse the response since it's now JSON:

```python
data.json['player']['username']
```

I've been messing with this particular API quite a bit recently and wanted to drop by. Hopefully, this can help get this issue resolved
